### ISSUE TITLE
Contao 4: Datenbanktabellen werden nicht erstellt

### ISSUE THREAD

**Issue by Jaaaan** [wangaz/contao-jquery-ui-tabs#10]
Danke erstmal für #9 !

Im Contao-Manager kann man nun die Erweiterung auch finden und in einer gewissen Weise installieren. Die Installation verursacht keine Probleme, jedoch lassen sich mit dem Installtool nicht die DB-Tabellen erstellen.

Ich habe die Vermutung, dass die `sources` aufgrund der neuen Ordnerstruktur unter Contao 4 nicht richtig geladen werden können. Wäre eventuell die gleiche Herangehensweise wie bei `wangaz/contao-isotope-wirecard` denkbar, also z. B. mit `psr-0`?
Beispielsweise werden die Symlinks nicht erstellt.

Danke nochmals!

**Comment by thku** [comment]
Gibt es denn im Log eine entsprechende Fehlermeldung?

**Comment by Jaaaan** [comment]
Nein, es gibt keinen Log dazu. 
Der Contao-Manager kann die Erweiterung erfolgreich registrieren, legt jedoch nicht die entsprechenden Verzeichnisse/Symlinks unter `system/modules` bzw. `web/system/modules` an. 
Im `vendor `Verzeichnis liegt jedoch das gesamte Paket so wie es sein soll.

**Comment by Jaaaan** [comment]
Ich habe nochmal nachgeschaut, ein Fehlerlog wird nicht erstellt.

Normalerweise sollte unter `system/modules` ein Symlink (`jquery-ui-tabs`) erzeugt werden, welcher auf `vendor/wangaz/contao-jquery-ui-tabs/src/system/modules/jquery-ui-tabs` zeigt. 

Außerdem sollte das Verzeichnis `src/assets/jquery-ui-tabs` nach `assets` übernommen werden bzw. ein Symlink dort erstellt werden, welcher auf `vendor/wangaz/contao-jquery-ui-tabs/src/assets/jquery-ui-tabs` zeigt. Also so, wie es in der `composer.json` steht.

Beides ist nicht der Fall. 
Ich vermute mal, der Composer kann nichts mit 
```
"extra":{
"contao": {
"symlinks":{
```
anfangen?

**Comment by Jaaaan** [comment]
Tatsächlich muss es `sources` statt `symlinks` heißen: https://github.com/wangaz/contao-jquery-ui-tabs/blob/master/composer.json#L29

Nach einem Test wurden dann die entsprechenden Symlinks angelegt:
1) Unter `assets` wurde ein Symlink `jquery-ui-tabs` erstellt, welcher auf `/vendor/.../src/assets/jquery-ui-tabs` zeigt und

2) Unter `system/modules` wurde ein Symlink erstellt, welcher auf `/vendor/.../src/system/modules/jquery-ui-tabs` zeigt.

Ob 1) ganz so schön ist, kann ich nicht beurteilen. Eventuell müsste man die Ordnerstruktur überdenken, sodass irgendwie über das `/web` Verzeichnis die `assets` im `vendor-Verzeichnis` erreicht werden können. 
Außerdem müsste man schauen, ob die Erweiterung dann noch unter Contao 3 funktioniert.

Siehe auch #11

**Comment by fritzmg** [comment]
Punkt 1) ist normal und soll auch so sein.
