### ISSUE TITLE
Installation in Contao Version 4.4.33 funktioniert nicht

### ISSUE THREAD

**Issue by IsoldeNagel** [wangaz/contao-jquery-ui-tabs#14]
Anscheinend ist der Fehler vom 15.10.2017 immer noch da? 
Beim Anlegen von Tabs erscheint folgende Fehlermeldung. Aus dem alten Ticket erschließt sich für mich in keiner Weise, wie das Problem zu lösen ist. Vielen Dank für Hilfestellung.
 
![screenshot-draft9 creactiv-web com-2019 02 01-18-06-42](https://user-images.githubusercontent.com/47253905/52138117-91fa9800-264c-11e9-9333-ea69e38c57a6.png)
![tabs](https://user-images.githubusercontent.com/47253905/52138219-d423d980-264c-11e9-898a-b1aec6393c9c.png)

**Comment by thku** [comment]
Existieren denn die oben genannten Felder in der Datenbank?
Also in Tabelle *tl_content* z.B. *juiTabHeadline*
