### ISSUE TITLE
Neues Update - DB Syntax Error

### ISSUE THREAD

**Issue by Himalaya-0** [wangaz/contao-jquery-ui-tabs#15]
Guten Tag

Ich bin eher etwas neu mit Contao und in der Webentwicklung allgemein unterwegs und habe eine Frage betreffend dem neuen Update.
Die jquery-ui-tabs habe ich gestern am 04.03.2019 über den Contao Manager integriert und sie funktionieren auch.
Heute habe ich gesehen, dass ich die jquery-ui-tabs aktualisieren kann, was ich dann auch gemacht habe.

Leider kann ich aber die DB nicht aktualisieren nachdem Update. Wenn ich im Log nachschauen gehe, dann gibt er mir einen Syntaxerror zurück.

[2019-03-05 15:43:31] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 

'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation 
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = 'test_prod_de' AND TABLE_NAME = 'tl_layout' 
ORDER BY ORDINAL_POSITION ASC AND COLUMN_NAME = 'sections'':\n\nSQLSTATE[42000]:

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 
'AND COLUMN_NAME = 'sections'' at line 1 at /var/www/testsystem-tradepro/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: 

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 
'AND COLUMN_NAME = 'sections'' at line 1 at /var/www/testsystem-tradepro/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:90, PDOException(code: 42000): SQLSTATE[42000]: 

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 
'AND COLUMN_NAME = 'sections'' at line 1 at /var/www/testsystem-tradepro/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88)"} []

Kann es sein, dass bei diesen neuen Änderungen noch ein kleiner Fehler vorhanden ist?

Vielen Dank für die Antwort.

Freundliche Grüsse
Kimo

**Comment by thku** [comment]
Hmmm…
Da das letzte Update m.W. nicht heute herauskam: Welche Version der ui-Tabs ist denn installiert? Und welche Version von Contao?
Wurde das Install-Tool zum Aktualisieren der Datenbank fehlerfrei ausgeführt?

**Comment by Himalaya-0** [comment]
Also die Version die ich jetzt installiert habe ist 1.1.5. Ohne die DB zu aktualisieren.
Leider weiss ich nicht welche Version ich gestern installiert habe.
Das Contao hat die Version 4.4.26.
Sobald ich beim Install-Tool das PW eingebe kommt dann die Fehlermeldung.

**Comment by thku** [comment]
Ich bin unsicher, ob das direkt mit den jQuery-Tabs zu tun hat. Denn die werden z.B. im Installtool nicht benötigt oder geladen und dürften somit keine Probleme verursachen.
Es scheint sich also eher um ein Contao-Problem zu handeln.

Da es zuvor funktioniert hat und Doctrine mit Contao 4.X so seine Probleme hat, würde ich vorschlagen folgendes in die composer.json einzutragen:

```
    "conflict": {
        "doctrine/dbal": "2.9.*"
    }
```
Siehe z.B. [hier](https://github.com/contao/contao/issues/212)

**Comment by Himalaya-0** [comment]
Ach so, gut zu wissen. :)
Welche composer.json muss ich dann anpassen?
Ich habe z.B. bei doctrine/doctrine-bundle/composer.json - "doctrine/dbal": "^2.5.12",
oder bei contao/core-bundle/composer.json - "doctrine/dbal": "^2.5".
Bei smyfony/symfony/composer.json sogar - "doctrine/dbal": "~2.4"

**Comment by thku** [comment]
immer im Hauptverzeichnis der Contao-Installation. Alles andere wird bei Updates überschrieben. Da sollte auch schon ein entsprechender Abschnitt stehen und hinzufügen muss man wirklich nur doctrine/dbal als Zeile.

**Comment by Himalaya-0** [comment]
Super, vielen Dank für die Hilfe.
Ich habe jetzt im Ordner vendor/contao/core-bundle/composer.json die doctrine/dbal angepasst.
Ich nehme an das ist das Hauptverzeichnis?
Falls ja, dann hat es leider nichts gebracht.
Oder was wäre die Ordnerstruktur für das Hauptverzeichnis?

PS: Tut mir leid, ich kenne mich noch nicht so gut damit aus. 

Edit: Aso ich habe bei "conflict" "doctrine/dbal": "2.9.*" hinzugefügt. Dort gibt es bereits andere Begriffe.

**Comment by thku** [comment]
nein, das Hauptverzeichnis ist das vor /vendor/ (das ist ja bereits ein Unterverzeichnis):
1. /composer.json entsprechend aktualisieren
2a. In der Kommandozeile `composer update` bzw. `php composer.phar update` in dem Verzeichnis ausführen
2b. oder im Contao-Manager ein Update durchführen
3. Sollte alles klappen

**Comment by Himalaya-0** [comment]
Hat alles geklappt.
Vielen Dank!
