### ISSUE TITLE
Extentions with tabs

### ISSUE THREAD

**Issue by garyee** [wangaz/contao-jquery-ui-tabs#8]
I'am using the extension to place some tabs from the backend, but I also have a module that uses jquery ui tabs by initalizing them from a template by:
`$(document).ready(function(){
                $('.tabs').tabs();
 });`
At first everything works fine, but then the first XHR call is made and it throws an error (in Firefox 52.0.2):

`Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/`
(German Error because of german browser)

**Comment by 7FyOh** [comment]
This extension is not loading any content via XHR, so I cannot imagine how this exception is thrown by this extension.

**Comment by garyee** [comment]
Yes you are right. Got the old Jquery Ui Tab - [base tag](https://bugs.jqueryui.com/ticket/8637) confusion. Sorry! now all works fine.
